GET http://localhost:8080/module HTTP/1.1
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huQHNtaXRoLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDM1NTAwN30.kOWMaRespoYIOvPmz1jBdsPqZpTH70KwAK5mWEQErQ8"

###

POST http://localhost:8080/module HTTP/1.1
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huQHNtaXRoLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDM1NTAwN30.kOWMaRespoYIOvPmz1jBdsPqZpTH70KwAK5mWEQErQ8"

{
    "moduleId": 3,
    "topic": "SpringBoot",
    "startDate": "2023-04-08",
    "endDate": "2023-04-15",
    "exerciseAmount": 4,
    "lessonAmount": 4
  }

###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json 

{
  "username" : "john@smith.com",
  "password": "P@ssw0rd!"
}

###
DELETE http://localhost:8080/module/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huQHNtaXRoLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDM1NTk5Nn0.SCAEE4mNswgzRbw5U2zVKWotxA_9v9yIYc0uguCyfbs

###
GET http://localhost:8080/cohort HTTP/1.1

###
POST http://localhost:8080/cohort HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJIVEQtQkFDS0VORCIsInN1YiI6ImpvaG5Ac21pdGguY29tIiwiYXV0aG9yaXRpZXMiOiJST0xFX0FETUlOIiwiZXhwIjoxNjg0MzU3MTkwfQ.ETILBRF9Sp5bucj_PrFrNizTx00Igyb99_iNfIaweSs

{
    "cohortId": 0,
    "startDate": "2024-01-01",
    "endDate": "2024-03-01",
    "client": {
      "clientId": 1,
      "clientName": "Main bank",
      "address": "One Main st",
      "companySize": 1000,
      "email": "info@mainbank.com"
    },
    "instructor": {
      "instructorId": 1,
      "firstName": "James",
      "lastname": "Bond",
      "yearsOfExperience": 30,
      "expertise": "espionage",
      "salary": 30000.00
    },
    "contractors": [],
    "modules": []
  }